CREATE TABLE cliente
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(255)                            NOT NULL,
    lastname  VARCHAR(255)                            NOT NULL,
    cpf       VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    zipcode   VARCHAR(255)                            NOT NULL,
    street    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

ALTER TABLE cliente
    ADD CONSTRAINT uc_cliente_cpf UNIQUE (cpf);

ALTER TABLE cliente
    ADD CONSTRAINT uc_cliente_email UNIQUE (email);